### ISSUE TITLE
Block harvesting with tools got cancelled and generates silent crash

### ISSUE THREAD

**Issue by ChromaPIE** [Bedrockbreaker/Graduated-Cylinders#2]
Happens with worlds of instances without Mekanism, and the absense of Mekanism might be the exact cause of it.

Crash report: https://mclo.gs/Vt3ker4

It's a silent crash that doesnt actually crashes the client/server but only generates in the console upon left clicking on blocks. Issue wont happen when breaking blocks with bear hand.

**Comment by Bedrockbreaker** [comment]
Rip, I probably should've bug tested this more without mekanism installed. This should be fixed by the next update.

**Comment by Bedrockbreaker** [comment]
Fixed in 2.6.3
