### ISSUE TITLE
Verify new additions to Simplified Chinese .lang file

### ISSUE THREAD

**Issue by Bedrockbreaker** [Bedrockbreaker/Graduated-Cylinders#7]
Need verification for 5 new lines added to the Simplified Chinese .lang file.
They were originally obtained by translating the corresponding Japanese lines through Google Translate.

[src/main/resources/assets/graduatedcylinders/lang/zh_cn.lang](https://github.com/Bedrockbreaker/Graduated-Cylinders/blob/main/src/main/resources/assets/graduatedcylinders/lang/zh_cn.lang)
```
gc.gui.cycle=[TAB]：下一种液体
...
gc.gui.selectfluid=%2$s单击选择
gc.gui.selected=%s选择
gc.gui.fluidblocked=%s▌ %s不能运输
gc.gui.sideblocked=%s▌ %s无法选择
```

**Comment by Bedrockbreaker** [comment]
Additional lines which need verification:

```
gc.gui.16mb=1 粒
gc.gui.72mb=1/2 锭
gc.gui.144mb=1 锭
gc.gui.1296mb=9 锭
gc.gui.9216mb=64 锭

gc.gui.ingot=%s 锭
gc.gui.ingot.short=%s 锭
gc.gui.nugget=%s 粒
gc.gui.nugget.short=%s 粒

gc.gui.ingottoggle=切换锭模式
gc.gui.ingotmode=[SHIFT+%s]
```

**Comment by ChromaPIE** [comment]
me again.

it's basically good enough but i actually made some small changes
dont really have to open a pull request for it so i just put it on gist: https://gist.github.com/ChromaPIE/07194484fa542f1f28eca144456efe8c

**Comment by Bedrockbreaker** [comment]
Fair enough, lol. Thanks for your effort!
