### ISSUE TITLE
Crash when left-clicking certain blocks like EnderIO fluid conduits

### ISSUE THREAD

**Issue by ZZZank** [Bedrockbreaker/Graduated-Cylinders#9]
The title should be enough for illustrating the whole issue. 
This also happens on Advanced Seared Drain from Smeltery IO, but crash reason not exactly the same, I will provide crash logs for both of them.

[EnderIO(Ender Fluid Conduit)](https://github.com/user-attachments/files/16828234/crash-2024-09-01_16.59.11-client.txt)

[SmelteryIO(Advanced Seared Drain)](https://github.com/user-attachments/files/16828235/crash-2024-09-01_17.12.55-client.txt)

**Comment by MCTian-mi** [comment]
[GTCEu(Coke oven hatch)](https://mclo.gs/gPtbSlc) as well
probably because of some TEs isn't implementing `getTankProperties` properly
